<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.13 ./static/models/github-fluid.glb --transform
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();
	const initialScale = 30;

	const gltf = useGltf('/models/github-fluid-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.circle4.geometry}
			material={gltf.materials['SVGMat.010']}
			position={[0.0 * initialScale, 0.0 * initialScale, 0 * initialScale]}
			rotation={[Math.PI / 2, 0, 0]}
			scale={initialScale}
		/>
		<T.Mesh
			geometry={gltf.nodes.path4.geometry}
			material={gltf.materials['SVGMat.012']}
			position={[-0.017 * initialScale, -0.02 * initialScale, 0 * initialScale]}
			rotation={[Math.PI / 2, 0, 0]}
			scale={initialScale}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>

<!-- position={[0.06 * initialScale, 0.06 * initialScale, 0 * initialScale]}

position={[0.045 * initialScale, 0.04 * initialScale, 0 * initialScale]} -->
