name: Linting and Dependency Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  run-checks:
    name: Run checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3.5.3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install Node.js dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          eslint: true
          prettier: true

      - name: Run dependency check
        run: npx depcheck
